# -*- coding: utf-8 -*-
import time

# Form implementation generated from reading ui file 'ui/calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):

        def add1():
            self.lineEdit.setText(self.lineEdit.text()+"1")

        def add2():
            self.lineEdit.setText(self.lineEdit.text()+"2")

        def add3():
            self.lineEdit.setText(self.lineEdit.text()+"3")

        def add4():
            self.lineEdit.setText(self.lineEdit.text()+"4")

        def add5():
            self.lineEdit.setText(self.lineEdit.text()+"5")

        def add6():
            self.lineEdit.setText(self.lineEdit.text()+"6")

        def add7():
            self.lineEdit.setText(self.lineEdit.text()+"7")

        def add8():
            self.lineEdit.setText(self.lineEdit.text()+"8")

        def add9():
            self.lineEdit.setText(self.lineEdit.text()+"9")

        def add0():
            self.lineEdit.setText(self.lineEdit.text()+"0")

        def times():
            self.lineEdit.setText(self.lineEdit.text()+"*")

        def r():
            self.lineEdit.setText(self.lineEdit.text()+"/")

        def dot():
            self.lineEdit.setText(self.lineEdit.text()+".")

        def O1():
            self.lineEdit.setText(self.lineEdit.text()+"(")

        def O2():
            self.lineEdit.setText(self.lineEdit.text()+")")


        def answer():
            if self.lineEdit.text() == "1000-7":
                self.lineEdit.setText("english or spanish?")
                return ":)"

            if self.lineEdit.text() == "sigma":
                self.lineEdit.setText("basek3124")
                return ":)"

            

            ansp = str(self.lineEdit.text())
            ans = str(eval(ansp))
            self.lineEdit.setText(ans)

        def plus():
            self.lineEdit.setText(self.lineEdit.text()+"+")

        def minus():
            self.lineEdit.setText(self.lineEdit.text()+"-")

        def c():
            self.lineEdit.setText("")



        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 411)


        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(20, 180, 75, 23))
        self.b1.setObjectName("b1")
        self.b1.clicked.connect(add1)
        self.bplus = QtWidgets.QPushButton(self.centralwidget)
        self.bplus.setGeometry(QtCore.QRect(200, 270, 75, 23))
        self.bplus.setObjectName("bplus")
        self.bplus.clicked.connect(plus)
        self.b4 = QtWidgets.QPushButton(self.centralwidget)
        self.b4.setGeometry(QtCore.QRect(20, 210, 75, 23))
        self.b4.setObjectName("b4")
        self.b4.clicked.connect(add4)
        self.b9 = QtWidgets.QPushButton(self.centralwidget)
        self.b9.setGeometry(QtCore.QRect(200, 240, 75, 23))
        self.b9.setObjectName("b9")
        self.b9.clicked.connect(add9)
        self.b5 = QtWidgets.QPushButton(self.centralwidget)
        self.b5.setGeometry(QtCore.QRect(110, 210, 75, 23))
        self.b5.setObjectName("b5")
        self.b5.clicked.connect(add5)
        self.b3 = QtWidgets.QPushButton(self.centralwidget)
        self.b3.setGeometry(QtCore.QRect(200, 180, 75, 23))
        self.b3.setObjectName("b3")
        self.b3.clicked.connect(add3)
        self.b6 = QtWidgets.QPushButton(self.centralwidget)
        self.b6.setGeometry(QtCore.QRect(200, 210, 75, 23))
        self.b6.setObjectName("b6")
        self.b6.clicked.connect(add6)
        self.b0 = QtWidgets.QPushButton(self.centralwidget)
        self.b0.setGeometry(QtCore.QRect(110, 270, 75, 23))
        self.b0.setObjectName("b0")
        self.b0.clicked.connect(add0)
        self.bminus = QtWidgets.QPushButton(self.centralwidget)
        self.bminus.setGeometry(QtCore.QRect(20, 270, 75, 23))
        self.bminus.setObjectName("bminus")
        self.bminus.clicked.connect(minus)
        self.b7 = QtWidgets.QPushButton(self.centralwidget)
        self.b7.setGeometry(QtCore.QRect(20, 240, 75, 23))
        self.b7.setObjectName("b7")
        self.b7.clicked.connect(add7)
        self.p2 = QtWidgets.QPushButton(self.centralwidget)
        self.p2.setGeometry(QtCore.QRect(110, 180, 75, 23))
        self.p2.setObjectName("p2")
        self.p2.clicked.connect(add2)
        self.b8 = QtWidgets.QPushButton(self.centralwidget)
        self.b8.setGeometry(QtCore.QRect(110, 240, 75, 23))
        self.b8.setObjectName("b8")
        self.b8.clicked.connect(add8)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 70, 251, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.br = QtWidgets.QPushButton(self.centralwidget)
        self.br.setGeometry(QtCore.QRect(110, 300, 75, 23))
        self.br.setObjectName("br")
        self.br.clicked.connect(answer)
        self.C = QtWidgets.QPushButton(self.centralwidget)
        self.C.setGeometry(QtCore.QRect(110, 360, 75, 23))
        self.C.setObjectName("C")
        self.C.clicked.connect(c)
        self.r = QtWidgets.QPushButton(self.centralwidget)
        self.r.setGeometry(QtCore.QRect(20, 300, 75, 23))
        self.r.setObjectName("r")
        self.r.clicked.connect(r)
        self.times = QtWidgets.QPushButton(self.centralwidget)
        self.times.setGeometry(QtCore.QRect(200, 300, 75, 23))
        self.times.clicked.connect(times)
        self.dot = QtWidgets.QPushButton(self.centralwidget)
        self.dot.setGeometry(QtCore.QRect(110, 330, 75, 23))
        self.dot.setObjectName("dot")
        self.dot.clicked.connect(dot)
        self.O1 = QtWidgets.QPushButton(self.centralwidget)
        self.O1.setGeometry(QtCore.QRect(20, 330, 75, 23))
        self.O1.setObjectName("O1")
        self.O1.clicked.connect(O1)
        self.O2 = QtWidgets.QPushButton(self.centralwidget)
        self.O2.setGeometry(200, 330, 75, 23)
        self.O2.clicked.connect(O2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)




        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b1.setText(_translate("MainWindow", "1"))
        self.bplus.setText(_translate("MainWindow", "+"))
        self.b4.setText(_translate("MainWindow", "4"))
        self.b9.setText(_translate("MainWindow", "9"))
        self.b5.setText(_translate("MainWindow", "5"))
        self.b3.setText(_translate("MainWindow", "3"))
        self.b6.setText(_translate("MainWindow", "6"))
        self.b0.setText(_translate("MainWindow", "0"))
        self.bminus.setText(_translate("MainWindow", "--"))
        self.b7.setText(_translate("MainWindow", "7"))
        self.p2.setText(_translate("MainWindow", "2"))
        self.b8.setText(_translate("MainWindow", "8"))
        self.br.setText(_translate("MainWindow", "="))
        self.C.setText(_translate("MainWindow", "C"))
        self.r.setText(_translate("MainWindow", "/"))
        self.times.setText(_translate("MainWindow", "*"))
        self.dot.setText(_translate("MainWindow", "."))
        self.O1.setText(_translate("MainWindow", "("))
        self.O2.setText(_translate("MainWindow", ")"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
